# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'gmpWdGdFP.ui'
##
## Created by: Qt User Interface Compiler version 6.4.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QDialog, QFrame, QLabel,
    QLineEdit, QPushButton, QRadioButton, QSizePolicy,
    QWidget)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        if not Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(589, 362)
        self.bt_init = QPushButton(Dialog)
        self.bt_init.setObjectName(u"bt_init")
        self.bt_init.setGeometry(QRect(20, 130, 84, 27))
        self.bt_reboot = QPushButton(Dialog)
        self.bt_reboot.setObjectName(u"bt_reboot")
        self.bt_reboot.setGeometry(QRect(20, 90, 84, 27))
        self.bt_test = QPushButton(Dialog)
        self.bt_test.setObjectName(u"bt_test")
        self.bt_test.setGeometry(QRect(20, 50, 84, 27))
        self.bt_apply = QPushButton(Dialog)
        self.bt_apply.setObjectName(u"bt_apply")
        self.bt_apply.setGeometry(QRect(20, 170, 84, 27))
        self.bt_observe = QPushButton(Dialog)
        self.bt_observe.setObjectName(u"bt_observe")
        self.bt_observe.setGeometry(QRect(20, 210, 84, 27))
        self.bt_abort = QPushButton(Dialog)
        self.bt_abort.setObjectName(u"bt_abort")
        self.bt_abort.setGeometry(QRect(20, 250, 84, 27))
        self.e_expTime = QLineEdit(Dialog)
        self.e_expTime.setObjectName(u"e_expTime")
        self.e_expTime.setGeometry(QRect(190, 170, 51, 26))
        self.label = QLabel(Dialog)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(120, 174, 71, 19))
        self.radio_acq = QRadioButton(Dialog)
        self.radio_acq.setObjectName(u"radio_acq")
        self.radio_acq.setGeometry(QRect(260, 170, 51, 25))
        self.radio_sci = QRadioButton(Dialog)
        self.radio_sci.setObjectName(u"radio_sci")
        self.radio_sci.setGeometry(QRect(320, 170, 51, 25))
        self.e_ActionID = QLineEdit(Dialog)
        self.e_ActionID.setObjectName(u"e_ActionID")
        self.e_ActionID.setGeometry(QRect(110, 16, 71, 26))
        self.label_2 = QLabel(Dialog)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(30, 20, 71, 19))
        self.e_send = QLineEdit(Dialog)
        self.e_send.setObjectName(u"e_send")
        self.e_send.setGeometry(QRect(30, 290, 341, 26))
        self.e_send.setReadOnly(True)
        self.e_recv = QLineEdit(Dialog)
        self.e_recv.setObjectName(u"e_recv")
        self.e_recv.setGeometry(QRect(30, 320, 341, 26))
        self.e_recv.setReadOnly(True)
        self.label_3 = QLabel(Dialog)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 290, 21, 19))
        self.label_4 = QLabel(Dialog)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 320, 21, 19))
        self.line = QFrame(Dialog)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(373, 10, 20, 341))
        self.line.setFrameShape(QFrame.VLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.label_5 = QLabel(Dialog)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(420, 24, 71, 19))
        self.label_5.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.e_port = QLineEdit(Dialog)
        self.e_port.setObjectName(u"e_port")
        self.e_port.setGeometry(QRect(500, 20, 71, 26))
        self.e_currentRMA = QLineEdit(Dialog)
        self.e_currentRMA.setObjectName(u"e_currentRMA")
        self.e_currentRMA.setGeometry(QRect(500, 50, 71, 26))
        self.label_6 = QLabel(Dialog)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(400, 54, 91, 20))
        self.label_6.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.e_positionAngle = QLineEdit(Dialog)
        self.e_positionAngle.setObjectName(u"e_positionAngle")
        self.e_positionAngle.setGeometry(QRect(500, 80, 71, 26))
        self.e_currentDec = QLineEdit(Dialog)
        self.e_currentDec.setObjectName(u"e_currentDec")
        self.e_currentDec.setGeometry(QRect(500, 140, 71, 26))
        self.e_currentRA = QLineEdit(Dialog)
        self.e_currentRA.setObjectName(u"e_currentRA")
        self.e_currentRA.setGeometry(QRect(500, 110, 71, 26))
        self.label_8 = QLabel(Dialog)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(400, 114, 91, 20))
        self.label_8.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_9 = QLabel(Dialog)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(400, 144, 91, 20))
        self.label_9.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_10 = QLabel(Dialog)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(420, 84, 71, 19))
        self.label_10.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_11 = QLabel(Dialog)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(400, 174, 91, 20))
        self.label_11.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.e_airMass = QLineEdit(Dialog)
        self.e_airMass.setObjectName(u"e_airMass")
        self.e_airMass.setGeometry(QRect(500, 170, 71, 26))
        self.label_12 = QLabel(Dialog)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(400, 204, 91, 20))
        self.label_12.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.e_HourAngle = QLineEdit(Dialog)
        self.e_HourAngle.setObjectName(u"e_HourAngle")
        self.e_HourAngle.setGeometry(QRect(500, 200, 71, 26))
        self.e_localSiderealTime = QLineEdit(Dialog)
        self.e_localSiderealTime.setObjectName(u"e_localSiderealTime")
        self.e_localSiderealTime.setGeometry(QRect(500, 230, 71, 26))
        self.label_13 = QLabel(Dialog)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(400, 234, 91, 20))
        self.label_13.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.e_zenithDistance = QLineEdit(Dialog)
        self.e_zenithDistance.setObjectName(u"e_zenithDistance")
        self.e_zenithDistance.setGeometry(QRect(500, 260, 71, 26))
        self.label_14 = QLabel(Dialog)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(400, 264, 91, 20))
        self.label_14.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.bt_send_fromGemini = QPushButton(Dialog)
        self.bt_send_fromGemini.setObjectName(u"bt_send_fromGemini")
        self.bt_send_fromGemini.setGeometry(QRect(400, 293, 171, 51))

        self.retranslateUi(Dialog)

        QMetaObject.connectSlotsByName(Dialog)
    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"GMP", None))
        self.bt_init.setText(QCoreApplication.translate("Dialog", u"INIT", None))
        self.bt_reboot.setText(QCoreApplication.translate("Dialog", u"REBOOT", None))
        self.bt_test.setText(QCoreApplication.translate("Dialog", u"TEST", None))
        self.bt_apply.setText(QCoreApplication.translate("Dialog", u"APPLY", None))
        self.bt_observe.setText(QCoreApplication.translate("Dialog", u"OBSERVE", None))
        self.bt_abort.setText(QCoreApplication.translate("Dialog", u"ABORT", None))
        self.label.setText(QCoreApplication.translate("Dialog", u"Exp.Time:", None))
        self.radio_acq.setText(QCoreApplication.translate("Dialog", u"ACQ", None))
        self.radio_sci.setText(QCoreApplication.translate("Dialog", u"SCI", None))
        self.label_2.setText(QCoreApplication.translate("Dialog", u"Action ID:", None))
        self.label_3.setText(QCoreApplication.translate("Dialog", u">>", None))
        self.label_4.setText(QCoreApplication.translate("Dialog", u"<<", None))
        self.label_5.setText(QCoreApplication.translate("Dialog", u"port:", None))
        self.label_6.setText(QCoreApplication.translate("Dialog", u"current RMA:", None))
        self.label_8.setText(QCoreApplication.translate("Dialog", u"current RA:", None))
        self.label_9.setText(QCoreApplication.translate("Dialog", u"current Dec:", None))
        self.label_10.setText(QCoreApplication.translate("Dialog", u"PA:", None))
        self.label_11.setText(QCoreApplication.translate("Dialog", u"airMass:", None))
        self.label_12.setText(QCoreApplication.translate("Dialog", u"HA:", None))
        self.label_13.setText(QCoreApplication.translate("Dialog", u"LST:", None))
        self.label_14.setText(QCoreApplication.translate("Dialog", u"ZD:", None))
        self.bt_send_fromGemini.setText(QCoreApplication.translate("Dialog", u"Send", None))
    # retranslateUi

