# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'DTPEVFATv.ui'
##
## Created by: Qt User Interface Compiler version 6.3.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QDialog, QFrame,
    QGroupBox, QLabel, QLineEdit, QProgressBar,
    QPushButton, QRadioButton, QSizePolicy, QWidget)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        if not Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(1314, 703)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.groupBox_8 = QGroupBox(Dialog)
        self.groupBox_8.setObjectName(u"groupBox_8")
        self.groupBox_8.setGeometry(QRect(350, 87, 331, 604))
        font = QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.groupBox_8.setFont(font)
        self.e_repeatH = QLineEdit(self.groupBox_8)
        self.e_repeatH.setObjectName(u"e_repeatH")
        self.e_repeatH.setGeometry(QRect(260, 376, 51, 21))
        font1 = QFont()
        font1.setPointSize(8)
        font1.setBold(True)
        self.e_repeatH.setFont(font1)
        self.e_repeatH.setAlignment(Qt.AlignCenter)
        self.e_exptimeH = QLineEdit(self.groupBox_8)
        self.e_exptimeH.setObjectName(u"e_exptimeH")
        self.e_exptimeH.setGeometry(QRect(130, 353, 51, 21))
        self.e_exptimeH.setFont(font1)
        self.e_exptimeH.setAlignment(Qt.AlignCenter)
        self.e_FSnumberH = QLineEdit(self.groupBox_8)
        self.e_FSnumberH.setObjectName(u"e_FSnumberH")
        self.e_FSnumberH.setGeometry(QRect(130, 376, 51, 21))
        self.e_FSnumberH.setFont(font1)
        self.e_FSnumberH.setAlignment(Qt.AlignCenter)
        self.label_23 = QLabel(self.groupBox_8)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(200, 376, 51, 20))
        font2 = QFont()
        font2.setPointSize(9)
        font2.setBold(True)
        self.label_23.setFont(font2)
        self.label_23.setLayoutDirection(Qt.LeftToRight)
        self.label_23.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_61 = QLabel(self.groupBox_8)
        self.label_61.setObjectName(u"label_61")
        self.label_61.setGeometry(QRect(280, 477, 41, 20))
        font3 = QFont()
        font3.setPointSize(9)
        font3.setBold(False)
        self.label_61.setFont(font3)
        self.label_61.setLayoutDirection(Qt.LeftToRight)
        self.label_61.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_57 = QLabel(self.groupBox_8)
        self.label_57.setObjectName(u"label_57")
        self.label_57.setGeometry(QRect(0, 437, 71, 20))
        self.label_57.setFont(font2)
        self.label_57.setLayoutDirection(Qt.LeftToRight)
        self.label_57.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_58 = QLabel(self.groupBox_8)
        self.label_58.setObjectName(u"label_58")
        self.label_58.setGeometry(QRect(0, 457, 71, 20))
        self.label_58.setFont(font2)
        self.label_58.setLayoutDirection(Qt.LeftToRight)
        self.label_58.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_prog_time_H = QLabel(self.groupBox_8)
        self.label_prog_time_H.setObjectName(u"label_prog_time_H")
        self.label_prog_time_H.setGeometry(QRect(80, 437, 241, 20))
        self.label_prog_time_H.setFont(font3)
        self.label_prog_time_H.setLayoutDirection(Qt.LeftToRight)
        self.label_prog_time_H.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.progressBar_H = QProgressBar(self.groupBox_8)
        self.progressBar_H.setObjectName(u"progressBar_H")
        self.progressBar_H.setGeometry(QRect(20, 477, 251, 20))
        self.progressBar_H.setFont(font2)
        self.progressBar_H.setValue(24)
        self.label_54 = QLabel(self.groupBox_8)
        self.label_54.setObjectName(u"label_54")
        self.label_54.setGeometry(QRect(0, 417, 71, 20))
        self.label_54.setFont(font2)
        self.label_54.setLayoutDirection(Qt.LeftToRight)
        self.label_54.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_prog_elapsed_H = QLabel(self.groupBox_8)
        self.label_prog_elapsed_H.setObjectName(u"label_prog_elapsed_H")
        self.label_prog_elapsed_H.setGeometry(QRect(80, 457, 61, 20))
        self.label_prog_elapsed_H.setFont(font3)
        self.label_prog_elapsed_H.setLayoutDirection(Qt.LeftToRight)
        self.label_prog_elapsed_H.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_prog_sts_H = QLabel(self.groupBox_8)
        self.label_prog_sts_H.setObjectName(u"label_prog_sts_H")
        self.label_prog_sts_H.setGeometry(QRect(80, 417, 131, 20))
        palette = QPalette()
        self.label_prog_sts_H.setPalette(palette)
        self.label_prog_sts_H.setFont(font3)
        self.label_prog_sts_H.setLayoutDirection(Qt.LeftToRight)
        self.label_prog_sts_H.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.line_9 = QFrame(self.groupBox_8)
        self.line_9.setObjectName(u"line_9")
        self.line_9.setGeometry(QRect(10, 397, 311, 20))
        self.line_9.setFont(font1)
        self.line_9.setFrameShape(QFrame.HLine)
        self.line_9.setFrameShadow(QFrame.Sunken)
        self.e_savefilename_H = QLineEdit(self.groupBox_8)
        self.e_savefilename_H.setObjectName(u"e_savefilename_H")
        self.e_savefilename_H.setGeometry(QRect(90, 570, 221, 21))
        self.e_savefilename_H.setFont(font2)
        self.checkBox_autosave_H = QCheckBox(self.groupBox_8)
        self.checkBox_autosave_H.setObjectName(u"checkBox_autosave_H")
        self.checkBox_autosave_H.setGeometry(QRect(110, 517, 131, 21))
        self.checkBox_autosave_H.setFont(font2)
        self.bt_save_H = QPushButton(self.groupBox_8)
        self.bt_save_H.setObjectName(u"bt_save_H")
        self.bt_save_H.setGeometry(QRect(250, 517, 61, 21))
        self.bt_save_H.setFont(font2)
        self.bt_path_H = QPushButton(self.groupBox_8)
        self.bt_path_H.setObjectName(u"bt_path_H")
        self.bt_path_H.setGeometry(QRect(20, 547, 61, 21))
        self.bt_path_H.setFont(font2)
        self.e_path_H = QLineEdit(self.groupBox_8)
        self.e_path_H.setObjectName(u"e_path_H")
        self.e_path_H.setGeometry(QRect(90, 547, 221, 21))
        self.e_path_H.setFont(font2)
        self.label_56 = QLabel(self.groupBox_8)
        self.label_56.setObjectName(u"label_56")
        self.label_56.setGeometry(QRect(20, 570, 61, 20))
        self.label_56.setFont(font3)
        self.label_56.setLayoutDirection(Qt.LeftToRight)
        self.label_56.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.chk_ds9_H = QCheckBox(self.groupBox_8)
        self.chk_ds9_H.setObjectName(u"chk_ds9_H")
        self.chk_ds9_H.setGeometry(QRect(20, 517, 81, 21))
        self.chk_ds9_H.setFont(font2)
        self.line_12 = QFrame(self.groupBox_8)
        self.line_12.setObjectName(u"line_12")
        self.line_12.setGeometry(QRect(10, 497, 311, 20))
        self.line_12.setFont(font1)
        self.line_12.setFrameShape(QFrame.HLine)
        self.line_12.setFrameShadow(QFrame.Sunken)
        self.label_cur_num_H = QLabel(self.groupBox_8)
        self.label_cur_num_H.setObjectName(u"label_cur_num_H")
        self.label_cur_num_H.setGeometry(QRect(209, 457, 61, 20))
        self.label_cur_num_H.setFont(font3)
        self.label_cur_num_H.setLayoutDirection(Qt.LeftToRight)
        self.label_cur_num_H.setAlignment(Qt.AlignCenter)
        self.bt_init_H = QPushButton(self.groupBox_8)
        self.bt_init_H.setObjectName(u"bt_init_H")
        self.bt_init_H.setGeometry(QRect(270, 417, 51, 21))
        self.bt_init_H.setFont(font2)
        self.frame_H = QFrame(self.groupBox_8)
        self.frame_H.setObjectName(u"frame_H")
        self.frame_H.setGeometry(QRect(0, 22, 331, 331))
        self.frame_H.setFrameShape(QFrame.NoFrame)
        self.frame_H.setFrameShadow(QFrame.Raised)
        self.radio_number_fowler_H = QRadioButton(self.groupBox_8)
        self.radio_number_fowler_H.setObjectName(u"radio_number_fowler_H")
        self.radio_number_fowler_H.setGeometry(QRect(20, 374, 101, 25))
        self.radio_exptime_H = QRadioButton(self.groupBox_8)
        self.radio_exptime_H.setObjectName(u"radio_exptime_H")
        self.radio_exptime_H.setGeometry(QRect(20, 351, 101, 25))
        self.groupBox_10 = QGroupBox(Dialog)
        self.groupBox_10.setObjectName(u"groupBox_10")
        self.groupBox_10.setGeometry(QRect(690, 87, 331, 604))
        self.groupBox_10.setFont(font)
        self.e_exptimeK = QLineEdit(self.groupBox_10)
        self.e_exptimeK.setObjectName(u"e_exptimeK")
        self.e_exptimeK.setGeometry(QRect(130, 353, 51, 21))
        self.e_exptimeK.setFont(font1)
        self.e_exptimeK.setAlignment(Qt.AlignCenter)
        self.e_FSnumberK = QLineEdit(self.groupBox_10)
        self.e_FSnumberK.setObjectName(u"e_FSnumberK")
        self.e_FSnumberK.setGeometry(QRect(130, 376, 51, 21))
        self.e_FSnumberK.setFont(font1)
        self.e_FSnumberK.setAlignment(Qt.AlignCenter)
        self.e_repeatK = QLineEdit(self.groupBox_10)
        self.e_repeatK.setObjectName(u"e_repeatK")
        self.e_repeatK.setGeometry(QRect(260, 376, 51, 21))
        self.e_repeatK.setFont(font1)
        self.e_repeatK.setAlignment(Qt.AlignCenter)
        self.label_76 = QLabel(self.groupBox_10)
        self.label_76.setObjectName(u"label_76")
        self.label_76.setGeometry(QRect(280, 477, 41, 20))
        self.label_76.setFont(font3)
        self.label_76.setLayoutDirection(Qt.LeftToRight)
        self.label_76.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_77 = QLabel(self.groupBox_10)
        self.label_77.setObjectName(u"label_77")
        self.label_77.setGeometry(QRect(0, 417, 71, 20))
        self.label_77.setFont(font2)
        self.label_77.setLayoutDirection(Qt.LeftToRight)
        self.label_77.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_prog_time_K = QLabel(self.groupBox_10)
        self.label_prog_time_K.setObjectName(u"label_prog_time_K")
        self.label_prog_time_K.setGeometry(QRect(80, 437, 241, 20))
        self.label_prog_time_K.setFont(font3)
        self.label_prog_time_K.setLayoutDirection(Qt.LeftToRight)
        self.label_prog_time_K.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_74 = QLabel(self.groupBox_10)
        self.label_74.setObjectName(u"label_74")
        self.label_74.setGeometry(QRect(0, 457, 71, 20))
        self.label_74.setFont(font2)
        self.label_74.setLayoutDirection(Qt.LeftToRight)
        self.label_74.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_73 = QLabel(self.groupBox_10)
        self.label_73.setObjectName(u"label_73")
        self.label_73.setGeometry(QRect(0, 437, 71, 20))
        self.label_73.setFont(font2)
        self.label_73.setLayoutDirection(Qt.LeftToRight)
        self.label_73.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.progressBar_K = QProgressBar(self.groupBox_10)
        self.progressBar_K.setObjectName(u"progressBar_K")
        self.progressBar_K.setGeometry(QRect(20, 477, 251, 20))
        self.progressBar_K.setFont(font2)
        self.progressBar_K.setValue(24)
        self.label_prog_elapsed_K = QLabel(self.groupBox_10)
        self.label_prog_elapsed_K.setObjectName(u"label_prog_elapsed_K")
        self.label_prog_elapsed_K.setGeometry(QRect(80, 457, 61, 20))
        self.label_prog_elapsed_K.setFont(font3)
        self.label_prog_elapsed_K.setLayoutDirection(Qt.LeftToRight)
        self.label_prog_elapsed_K.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_prog_sts_K = QLabel(self.groupBox_10)
        self.label_prog_sts_K.setObjectName(u"label_prog_sts_K")
        self.label_prog_sts_K.setGeometry(QRect(80, 417, 131, 20))
        palette1 = QPalette()
        self.label_prog_sts_K.setPalette(palette1)
        self.label_prog_sts_K.setFont(font3)
        self.label_prog_sts_K.setLayoutDirection(Qt.LeftToRight)
        self.label_prog_sts_K.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_24 = QLabel(self.groupBox_10)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(200, 376, 51, 20))
        self.label_24.setFont(font2)
        self.label_24.setLayoutDirection(Qt.LeftToRight)
        self.label_24.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.line_10 = QFrame(self.groupBox_10)
        self.line_10.setObjectName(u"line_10")
        self.line_10.setGeometry(QRect(10, 397, 311, 20))
        self.line_10.setFont(font1)
        self.line_10.setFrameShape(QFrame.HLine)
        self.line_10.setFrameShadow(QFrame.Sunken)
        self.e_savefilename_K = QLineEdit(self.groupBox_10)
        self.e_savefilename_K.setObjectName(u"e_savefilename_K")
        self.e_savefilename_K.setGeometry(QRect(90, 570, 221, 21))
        self.e_savefilename_K.setFont(font2)
        self.checkBox_autosave_K = QCheckBox(self.groupBox_10)
        self.checkBox_autosave_K.setObjectName(u"checkBox_autosave_K")
        self.checkBox_autosave_K.setGeometry(QRect(110, 517, 131, 21))
        self.checkBox_autosave_K.setFont(font2)
        self.bt_save_K = QPushButton(self.groupBox_10)
        self.bt_save_K.setObjectName(u"bt_save_K")
        self.bt_save_K.setGeometry(QRect(250, 517, 61, 21))
        self.bt_save_K.setFont(font2)
        self.bt_path_K = QPushButton(self.groupBox_10)
        self.bt_path_K.setObjectName(u"bt_path_K")
        self.bt_path_K.setGeometry(QRect(20, 547, 61, 21))
        self.bt_path_K.setFont(font2)
        self.e_path_K = QLineEdit(self.groupBox_10)
        self.e_path_K.setObjectName(u"e_path_K")
        self.e_path_K.setGeometry(QRect(90, 547, 221, 21))
        self.e_path_K.setFont(font2)
        self.label_59 = QLabel(self.groupBox_10)
        self.label_59.setObjectName(u"label_59")
        self.label_59.setGeometry(QRect(20, 570, 61, 20))
        self.label_59.setFont(font3)
        self.label_59.setLayoutDirection(Qt.LeftToRight)
        self.label_59.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.line_13 = QFrame(self.groupBox_10)
        self.line_13.setObjectName(u"line_13")
        self.line_13.setGeometry(QRect(10, 497, 311, 20))
        self.line_13.setFont(font1)
        self.line_13.setFrameShape(QFrame.HLine)
        self.line_13.setFrameShadow(QFrame.Sunken)
        self.chk_ds9_K = QCheckBox(self.groupBox_10)
        self.chk_ds9_K.setObjectName(u"chk_ds9_K")
        self.chk_ds9_K.setGeometry(QRect(20, 517, 81, 21))
        self.chk_ds9_K.setFont(font2)
        self.label_cur_num_K = QLabel(self.groupBox_10)
        self.label_cur_num_K.setObjectName(u"label_cur_num_K")
        self.label_cur_num_K.setGeometry(QRect(209, 457, 61, 20))
        self.label_cur_num_K.setFont(font3)
        self.label_cur_num_K.setLayoutDirection(Qt.LeftToRight)
        self.label_cur_num_K.setAlignment(Qt.AlignCenter)
        self.bt_init_K = QPushButton(self.groupBox_10)
        self.bt_init_K.setObjectName(u"bt_init_K")
        self.bt_init_K.setGeometry(QRect(270, 417, 51, 21))
        self.bt_init_K.setFont(font2)
        self.frame_K = QFrame(self.groupBox_10)
        self.frame_K.setObjectName(u"frame_K")
        self.frame_K.setGeometry(QRect(0, 22, 331, 331))
        self.frame_K.setFrameShape(QFrame.NoFrame)
        self.frame_K.setFrameShadow(QFrame.Raised)
        self.radio_exptime_K = QRadioButton(self.groupBox_10)
        self.radio_exptime_K.setObjectName(u"radio_exptime_K")
        self.radio_exptime_K.setGeometry(QRect(20, 351, 101, 25))
        self.radio_number_fowler_K = QRadioButton(self.groupBox_10)
        self.radio_number_fowler_K.setObjectName(u"radio_number_fowler_K")
        self.radio_number_fowler_K.setGeometry(QRect(20, 374, 101, 25))
        self.groupBox = QGroupBox(Dialog)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(1043, 40, 261, 651))
        self.groupBox.setFont(font)
        self.chk_whole = QCheckBox(self.groupBox)
        self.chk_whole.setObjectName(u"chk_whole")
        self.chk_whole.setGeometry(QRect(20, 40, 111, 31))
        self.chk_whole.setFont(font)
        self.bt_run = QPushButton(self.groupBox)
        self.bt_run.setObjectName(u"bt_run")
        self.bt_run.setGeometry(QRect(140, 40, 91, 31))
        self.bt_run.setFont(font2)
        self.groupBox_4 = QGroupBox(self.groupBox)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(10, 370, 241, 271))
        self.groupBox_4.setFont(font)
        self.bt_ltpos_set1 = QPushButton(self.groupBox_4)
        self.bt_ltpos_set1.setObjectName(u"bt_ltpos_set1")
        self.bt_ltpos_set1.setGeometry(QRect(190, 143, 41, 20))
        font4 = QFont()
        font4.setFamilies([u"Arial"])
        font4.setPointSize(9)
        font4.setBold(True)
        self.bt_ltpos_set1.setFont(font4)
        self.bt_utpos_set1 = QPushButton(self.groupBox_4)
        self.bt_utpos_set1.setObjectName(u"bt_utpos_set1")
        self.bt_utpos_set1.setGeometry(QRect(190, 53, 41, 20))
        self.bt_utpos_set1.setFont(font4)
        self.bt_utpos_set2 = QPushButton(self.groupBox_4)
        self.bt_utpos_set2.setObjectName(u"bt_utpos_set2")
        self.bt_utpos_set2.setGeometry(QRect(190, 75, 41, 20))
        self.bt_utpos_set2.setFont(font4)
        self.sts_lt_pos1_2 = QLabel(self.groupBox_4)
        self.sts_lt_pos1_2.setObjectName(u"sts_lt_pos1_2")
        self.sts_lt_pos1_2.setGeometry(QRect(120, 143, 61, 21))
        font5 = QFont()
        font5.setFamilies([u"Comic Sans MS"])
        font5.setPointSize(10)
        font5.setBold(False)
        font5.setItalic(False)
        self.sts_lt_pos1_2.setFont(font5)
        self.sts_lt_pos1_2.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.bt_ltpos_prev = QPushButton(self.groupBox_4)
        self.bt_ltpos_prev.setObjectName(u"bt_ltpos_prev")
        self.bt_ltpos_prev.setGeometry(QRect(16, 194, 21, 20))
        self.bt_ltpos_prev.setFont(font4)
        self.bt_ltpos_set4 = QPushButton(self.groupBox_4)
        self.bt_ltpos_set4.setObjectName(u"bt_ltpos_set4")
        self.bt_ltpos_set4.setGeometry(QRect(190, 209, 41, 20))
        self.bt_ltpos_set4.setFont(font4)
        self.bt_ltpos_set3 = QPushButton(self.groupBox_4)
        self.bt_ltpos_set3.setObjectName(u"bt_ltpos_set3")
        self.bt_ltpos_set3.setGeometry(QRect(190, 187, 41, 20))
        self.bt_ltpos_set3.setFont(font4)
        self.bt_ltpos_set2 = QPushButton(self.groupBox_4)
        self.bt_ltpos_set2.setObjectName(u"bt_ltpos_set2")
        self.bt_ltpos_set2.setGeometry(QRect(190, 165, 41, 20))
        self.bt_ltpos_set2.setFont(font4)
        self.bt_utpos_next = QPushButton(self.groupBox_4)
        self.bt_utpos_next.setObjectName(u"bt_utpos_next")
        self.bt_utpos_next.setGeometry(QRect(100, 64, 21, 20))
        self.bt_utpos_next.setFont(font4)
        self.bt_utpos_prev = QPushButton(self.groupBox_4)
        self.bt_utpos_prev.setObjectName(u"bt_utpos_prev")
        self.bt_utpos_prev.setGeometry(QRect(16, 64, 21, 20))
        self.bt_utpos_prev.setFont(font4)
        self.e_utpos = QLineEdit(self.groupBox_4)
        self.e_utpos.setObjectName(u"e_utpos")
        self.e_utpos.setGeometry(QRect(38, 64, 61, 20))
        self.e_utpos.setFont(font4)
        self.e_utpos.setLayoutDirection(Qt.LeftToRight)
        self.e_utpos.setAlignment(Qt.AlignCenter)
        self.line_2 = QFrame(self.groupBox_4)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(10, 97, 221, 20))
        self.line_2.setFont(font2)
        self.line_2.setFrameShape(QFrame.HLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.e_ltpos = QLineEdit(self.groupBox_4)
        self.e_ltpos.setObjectName(u"e_ltpos")
        self.e_ltpos.setGeometry(QRect(38, 194, 61, 20))
        self.e_ltpos.setFont(font4)
        self.e_ltpos.setLayoutDirection(Qt.LeftToRight)
        self.e_ltpos.setAlignment(Qt.AlignCenter)
        self.bt_ltpos_next = QPushButton(self.groupBox_4)
        self.bt_ltpos_next.setObjectName(u"bt_ltpos_next")
        self.bt_ltpos_next.setGeometry(QRect(100, 194, 21, 20))
        self.bt_ltpos_next.setFont(font4)
        self.sts_ut_pos1_2 = QLabel(self.groupBox_4)
        self.sts_ut_pos1_2.setObjectName(u"sts_ut_pos1_2")
        self.sts_ut_pos1_2.setGeometry(QRect(120, 53, 61, 21))
        self.sts_ut_pos1_2.setFont(font5)
        self.sts_ut_pos1_2.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.sts_ut_pos2_2 = QLabel(self.groupBox_4)
        self.sts_ut_pos2_2.setObjectName(u"sts_ut_pos2_2")
        self.sts_ut_pos2_2.setGeometry(QRect(120, 75, 61, 21))
        self.sts_ut_pos2_2.setFont(font5)
        self.sts_ut_pos2_2.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.sts_lt_pos2_2 = QLabel(self.groupBox_4)
        self.sts_lt_pos2_2.setObjectName(u"sts_lt_pos2_2")
        self.sts_lt_pos2_2.setGeometry(QRect(120, 165, 61, 21))
        self.sts_lt_pos2_2.setFont(font5)
        self.sts_lt_pos2_2.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.sts_lt_pos3_2 = QLabel(self.groupBox_4)
        self.sts_lt_pos3_2.setObjectName(u"sts_lt_pos3_2")
        self.sts_lt_pos3_2.setGeometry(QRect(120, 187, 61, 20))
        self.sts_lt_pos3_2.setFont(font5)
        self.sts_lt_pos3_2.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.sts_lt_pos4_2 = QLabel(self.groupBox_4)
        self.sts_lt_pos4_2.setObjectName(u"sts_lt_pos4_2")
        self.sts_lt_pos4_2.setGeometry(QRect(120, 209, 61, 21))
        self.sts_lt_pos4_2.setFont(font5)
        self.sts_lt_pos4_2.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_3 = QLabel(self.groupBox_4)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 30, 120, 20))
        self.label_3.setFont(font)
        self.label_3.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_4 = QLabel(self.groupBox_4)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 121, 120, 20))
        self.label_4.setFont(font)
        self.label_4.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_16 = QLabel(self.groupBox_4)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(70, 240, 111, 21))
        font6 = QFont()
        font6.setFamilies([u"Cantarell"])
        font6.setPointSize(9)
        font6.setBold(True)
        font6.setItalic(False)
        self.label_16.setFont(font6)
        self.label_16.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.e_movinginterval = QLineEdit(self.groupBox_4)
        self.e_movinginterval.setObjectName(u"e_movinginterval")
        self.e_movinginterval.setGeometry(QRect(190, 240, 41, 20))
        self.e_movinginterval.setFont(font4)
        self.e_movinginterval.setLayoutDirection(Qt.LeftToRight)
        self.e_movinginterval.setAlignment(Qt.AlignCenter)
        self.bt_ut_motor_init = QPushButton(self.groupBox_4)
        self.bt_ut_motor_init.setObjectName(u"bt_ut_motor_init")
        self.bt_ut_motor_init.setGeometry(QRect(130, 30, 101, 21))
        self.bt_ut_motor_init.setFont(font2)
        self.bt_lt_motor_init = QPushButton(self.groupBox_4)
        self.bt_lt_motor_init.setObjectName(u"bt_lt_motor_init")
        self.bt_lt_motor_init.setGeometry(QRect(130, 120, 101, 21))
        self.bt_lt_motor_init.setFont(font2)
        self.chk_dark = QCheckBox(self.groupBox)
        self.chk_dark.setObjectName(u"chk_dark")
        self.chk_dark.setGeometry(QRect(20, 129, 111, 20))
        self.chk_dark.setFont(font2)
        self.chk_flat_on = QCheckBox(self.groupBox)
        self.chk_flat_on.setObjectName(u"chk_flat_on")
        self.chk_flat_on.setGeometry(QRect(20, 154, 111, 20))
        self.chk_flat_on.setFont(font2)
        self.chk_pinhole_ThAr = QCheckBox(self.groupBox)
        self.chk_pinhole_ThAr.setObjectName(u"chk_pinhole_ThAr")
        self.chk_pinhole_ThAr.setGeometry(QRect(20, 255, 111, 20))
        self.chk_pinhole_ThAr.setFont(font2)
        self.chk_ThAr = QCheckBox(self.groupBox)
        self.chk_ThAr.setObjectName(u"chk_ThAr")
        self.chk_ThAr.setGeometry(QRect(20, 205, 111, 20))
        self.chk_ThAr.setFont(font2)
        self.chk_flat_off = QCheckBox(self.groupBox)
        self.chk_flat_off.setObjectName(u"chk_flat_off")
        self.chk_flat_off.setGeometry(QRect(20, 179, 111, 20))
        self.chk_flat_off.setFont(font2)
        self.chk_pinhole_flat = QCheckBox(self.groupBox)
        self.chk_pinhole_flat.setObjectName(u"chk_pinhole_flat")
        self.chk_pinhole_flat.setGeometry(QRect(20, 229, 111, 21))
        self.chk_pinhole_flat.setFont(font2)
        self.chk_USAF_off = QCheckBox(self.groupBox)
        self.chk_USAF_off.setObjectName(u"chk_USAF_off")
        self.chk_USAF_off.setGeometry(QRect(20, 305, 111, 20))
        self.chk_USAF_off.setFont(font2)
        self.chk_USAF_on = QCheckBox(self.groupBox)
        self.chk_USAF_on.setObjectName(u"chk_USAF_on")
        self.chk_USAF_on.setGeometry(QRect(20, 280, 111, 20))
        self.chk_USAF_on.setFont(font2)
        self.chk_parking = QCheckBox(self.groupBox)
        self.chk_parking.setObjectName(u"chk_parking")
        self.chk_parking.setGeometry(QRect(20, 330, 111, 20))
        self.chk_parking.setFont(font2)
        self.label_67 = QLabel(self.groupBox)
        self.label_67.setObjectName(u"label_67")
        self.label_67.setGeometry(QRect(20, 100, 81, 20))
        self.label_67.setFont(font)
        self.label_67.setLayoutDirection(Qt.LeftToRight)
        self.label_67.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_68 = QLabel(self.groupBox)
        self.label_68.setObjectName(u"label_68")
        self.label_68.setGeometry(QRect(110, 100, 71, 20))
        self.label_68.setFont(font)
        self.label_68.setLayoutDirection(Qt.LeftToRight)
        self.label_68.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_80 = QLabel(self.groupBox)
        self.label_80.setObjectName(u"label_80")
        self.label_80.setGeometry(QRect(190, 100, 51, 20))
        self.label_80.setFont(font)
        self.label_80.setLayoutDirection(Qt.LeftToRight)
        self.label_80.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.e_dark_exptime = QLineEdit(self.groupBox)
        self.e_dark_exptime.setObjectName(u"e_dark_exptime")
        self.e_dark_exptime.setGeometry(QRect(130, 129, 51, 20))
        self.e_dark_exptime.setFont(font2)
        self.e_dark_exptime.setAlignment(Qt.AlignCenter)
        self.e_flaton_exptime = QLineEdit(self.groupBox)
        self.e_flaton_exptime.setObjectName(u"e_flaton_exptime")
        self.e_flaton_exptime.setGeometry(QRect(130, 154, 51, 20))
        self.e_flaton_exptime.setFont(font2)
        self.e_flaton_exptime.setAlignment(Qt.AlignCenter)
        self.e_flatoff_exptime = QLineEdit(self.groupBox)
        self.e_flatoff_exptime.setObjectName(u"e_flatoff_exptime")
        self.e_flatoff_exptime.setGeometry(QRect(130, 179, 51, 20))
        self.e_flatoff_exptime.setFont(font2)
        self.e_flatoff_exptime.setAlignment(Qt.AlignCenter)
        self.e_ThAr_exptime = QLineEdit(self.groupBox)
        self.e_ThAr_exptime.setObjectName(u"e_ThAr_exptime")
        self.e_ThAr_exptime.setGeometry(QRect(130, 205, 51, 20))
        self.e_ThAr_exptime.setFont(font2)
        self.e_ThAr_exptime.setAlignment(Qt.AlignCenter)
        self.e_USAFon_exptime = QLineEdit(self.groupBox)
        self.e_USAFon_exptime.setObjectName(u"e_USAFon_exptime")
        self.e_USAFon_exptime.setGeometry(QRect(130, 280, 51, 20))
        self.e_USAFon_exptime.setFont(font2)
        self.e_USAFon_exptime.setAlignment(Qt.AlignCenter)
        self.e_pinholeflat_exptime = QLineEdit(self.groupBox)
        self.e_pinholeflat_exptime.setObjectName(u"e_pinholeflat_exptime")
        self.e_pinholeflat_exptime.setGeometry(QRect(130, 230, 51, 20))
        self.e_pinholeflat_exptime.setFont(font2)
        self.e_pinholeflat_exptime.setAlignment(Qt.AlignCenter)
        self.e_pinholeThAr_exptime = QLineEdit(self.groupBox)
        self.e_pinholeThAr_exptime.setObjectName(u"e_pinholeThAr_exptime")
        self.e_pinholeThAr_exptime.setGeometry(QRect(130, 255, 51, 20))
        self.e_pinholeThAr_exptime.setFont(font2)
        self.e_pinholeThAr_exptime.setAlignment(Qt.AlignCenter)
        self.e_USAFoff_exptime = QLineEdit(self.groupBox)
        self.e_USAFoff_exptime.setObjectName(u"e_USAFoff_exptime")
        self.e_USAFoff_exptime.setGeometry(QRect(130, 305, 51, 20))
        self.e_USAFoff_exptime.setFont(font2)
        self.e_USAFoff_exptime.setAlignment(Qt.AlignCenter)
        self.e_parking_exptime = QLineEdit(self.groupBox)
        self.e_parking_exptime.setObjectName(u"e_parking_exptime")
        self.e_parking_exptime.setGeometry(QRect(130, 330, 51, 20))
        self.e_parking_exptime.setFont(font2)
        self.e_parking_exptime.setAlignment(Qt.AlignCenter)
        self.e_flaton_repeat = QLineEdit(self.groupBox)
        self.e_flaton_repeat.setObjectName(u"e_flaton_repeat")
        self.e_flaton_repeat.setGeometry(QRect(200, 154, 41, 20))
        self.e_flaton_repeat.setFont(font2)
        self.e_flaton_repeat.setAlignment(Qt.AlignCenter)
        self.e_USAFoff_repeat = QLineEdit(self.groupBox)
        self.e_USAFoff_repeat.setObjectName(u"e_USAFoff_repeat")
        self.e_USAFoff_repeat.setGeometry(QRect(200, 305, 41, 20))
        self.e_USAFoff_repeat.setFont(font2)
        self.e_USAFoff_repeat.setAlignment(Qt.AlignCenter)
        self.e_flatoff_repeat = QLineEdit(self.groupBox)
        self.e_flatoff_repeat.setObjectName(u"e_flatoff_repeat")
        self.e_flatoff_repeat.setGeometry(QRect(200, 179, 41, 20))
        self.e_flatoff_repeat.setFont(font2)
        self.e_flatoff_repeat.setAlignment(Qt.AlignCenter)
        self.e_dark_repeat = QLineEdit(self.groupBox)
        self.e_dark_repeat.setObjectName(u"e_dark_repeat")
        self.e_dark_repeat.setGeometry(QRect(200, 129, 41, 20))
        self.e_dark_repeat.setFont(font2)
        self.e_dark_repeat.setAlignment(Qt.AlignCenter)
        self.e_pinholeflat_repeat = QLineEdit(self.groupBox)
        self.e_pinholeflat_repeat.setObjectName(u"e_pinholeflat_repeat")
        self.e_pinholeflat_repeat.setGeometry(QRect(200, 230, 41, 20))
        self.e_pinholeflat_repeat.setFont(font2)
        self.e_pinholeflat_repeat.setAlignment(Qt.AlignCenter)
        self.e_pinholeThAr_repeat = QLineEdit(self.groupBox)
        self.e_pinholeThAr_repeat.setObjectName(u"e_pinholeThAr_repeat")
        self.e_pinholeThAr_repeat.setGeometry(QRect(200, 255, 41, 20))
        self.e_pinholeThAr_repeat.setFont(font2)
        self.e_pinholeThAr_repeat.setAlignment(Qt.AlignCenter)
        self.e_parking_repeat = QLineEdit(self.groupBox)
        self.e_parking_repeat.setObjectName(u"e_parking_repeat")
        self.e_parking_repeat.setGeometry(QRect(200, 330, 41, 20))
        self.e_parking_repeat.setFont(font2)
        self.e_parking_repeat.setAlignment(Qt.AlignCenter)
        self.e_ThAr_repeat = QLineEdit(self.groupBox)
        self.e_ThAr_repeat.setObjectName(u"e_ThAr_repeat")
        self.e_ThAr_repeat.setGeometry(QRect(200, 205, 41, 20))
        self.e_ThAr_repeat.setFont(font2)
        self.e_ThAr_repeat.setAlignment(Qt.AlignCenter)
        self.e_USAFon_repeat = QLineEdit(self.groupBox)
        self.e_USAFon_repeat.setObjectName(u"e_USAFon_repeat")
        self.e_USAFon_repeat.setGeometry(QRect(200, 280, 41, 20))
        self.e_USAFon_repeat.setFont(font2)
        self.e_USAFon_repeat.setAlignment(Qt.AlignCenter)
        self.line_4 = QFrame(self.groupBox)
        self.line_4.setObjectName(u"line_4")
        self.line_4.setGeometry(QRect(20, 80, 221, 20))
        self.line_4.setFont(font2)
        self.line_4.setFrameShape(QFrame.HLine)
        self.line_4.setFrameShadow(QFrame.Sunken)
        self.groupBox_11 = QGroupBox(Dialog)
        self.groupBox_11.setObjectName(u"groupBox_11")
        self.groupBox_11.setGeometry(QRect(10, 87, 331, 604))
        self.groupBox_11.setFont(font)
        self.label_22 = QLabel(self.groupBox_11)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(200, 376, 51, 20))
        self.label_22.setFont(font2)
        self.label_22.setLayoutDirection(Qt.LeftToRight)
        self.label_22.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.e_repeat_number_svc = QLineEdit(self.groupBox_11)
        self.e_repeat_number_svc.setObjectName(u"e_repeat_number_svc")
        self.e_repeat_number_svc.setGeometry(QRect(260, 376, 51, 21))
        self.e_repeat_number_svc.setFont(font2)
        self.e_repeat_number_svc.setAlignment(Qt.AlignCenter)
        self.e_exptime_svc = QLineEdit(self.groupBox_11)
        self.e_exptime_svc.setObjectName(u"e_exptime_svc")
        self.e_exptime_svc.setGeometry(QRect(130, 353, 51, 21))
        self.e_exptime_svc.setFont(font2)
        self.e_exptime_svc.setAlignment(Qt.AlignCenter)
        self.e_FS_number_svc = QLineEdit(self.groupBox_11)
        self.e_FS_number_svc.setObjectName(u"e_FS_number_svc")
        self.e_FS_number_svc.setGeometry(QRect(130, 376, 51, 21))
        self.e_FS_number_svc.setFont(font2)
        self.e_FS_number_svc.setAlignment(Qt.AlignCenter)
        self.line_8 = QFrame(self.groupBox_11)
        self.line_8.setObjectName(u"line_8")
        self.line_8.setGeometry(QRect(10, 397, 311, 20))
        self.line_8.setFont(font1)
        self.line_8.setFrameShape(QFrame.HLine)
        self.line_8.setFrameShadow(QFrame.Sunken)
        self.label_29 = QLabel(self.groupBox_11)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(0, 417, 71, 20))
        self.label_29.setFont(font2)
        self.label_29.setLayoutDirection(Qt.LeftToRight)
        self.label_29.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_prog_stats_svc = QLabel(self.groupBox_11)
        self.label_prog_stats_svc.setObjectName(u"label_prog_stats_svc")
        self.label_prog_stats_svc.setGeometry(QRect(80, 417, 131, 20))
        palette2 = QPalette()
        self.label_prog_stats_svc.setPalette(palette2)
        self.label_prog_stats_svc.setFont(font3)
        self.label_prog_stats_svc.setLayoutDirection(Qt.LeftToRight)
        self.label_prog_stats_svc.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_25 = QLabel(self.groupBox_11)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(0, 437, 71, 20))
        self.label_25.setFont(font2)
        self.label_25.setLayoutDirection(Qt.LeftToRight)
        self.label_25.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.progressBar_svc = QProgressBar(self.groupBox_11)
        self.progressBar_svc.setObjectName(u"progressBar_svc")
        self.progressBar_svc.setGeometry(QRect(20, 477, 251, 20))
        self.progressBar_svc.setFont(font2)
        self.progressBar_svc.setValue(24)
        self.label_28 = QLabel(self.groupBox_11)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(0, 457, 71, 20))
        self.label_28.setFont(font2)
        self.label_28.setLayoutDirection(Qt.LeftToRight)
        self.label_28.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_prog_time_svc = QLabel(self.groupBox_11)
        self.label_prog_time_svc.setObjectName(u"label_prog_time_svc")
        self.label_prog_time_svc.setGeometry(QRect(80, 437, 241, 20))
        self.label_prog_time_svc.setFont(font3)
        self.label_prog_time_svc.setLayoutDirection(Qt.LeftToRight)
        self.label_prog_time_svc.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_prog_elapsed_svc = QLabel(self.groupBox_11)
        self.label_prog_elapsed_svc.setObjectName(u"label_prog_elapsed_svc")
        self.label_prog_elapsed_svc.setGeometry(QRect(80, 457, 61, 20))
        self.label_prog_elapsed_svc.setFont(font3)
        self.label_prog_elapsed_svc.setLayoutDirection(Qt.LeftToRight)
        self.label_prog_elapsed_svc.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_31 = QLabel(self.groupBox_11)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(280, 477, 41, 20))
        self.label_31.setFont(font3)
        self.label_31.setLayoutDirection(Qt.LeftToRight)
        self.label_31.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_cur_num_svc = QLabel(self.groupBox_11)
        self.label_cur_num_svc.setObjectName(u"label_cur_num_svc")
        self.label_cur_num_svc.setGeometry(QRect(209, 457, 61, 20))
        self.label_cur_num_svc.setFont(font3)
        self.label_cur_num_svc.setLayoutDirection(Qt.LeftToRight)
        self.label_cur_num_svc.setAlignment(Qt.AlignCenter)
        self.line_11 = QFrame(self.groupBox_11)
        self.line_11.setObjectName(u"line_11")
        self.line_11.setGeometry(QRect(10, 497, 311, 20))
        self.line_11.setFont(font1)
        self.line_11.setFrameShape(QFrame.HLine)
        self.line_11.setFrameShadow(QFrame.Sunken)
        self.checkBox_autosave_svc = QCheckBox(self.groupBox_11)
        self.checkBox_autosave_svc.setObjectName(u"checkBox_autosave_svc")
        self.checkBox_autosave_svc.setGeometry(QRect(110, 517, 131, 21))
        self.checkBox_autosave_svc.setFont(font2)
        self.bt_save_svc = QPushButton(self.groupBox_11)
        self.bt_save_svc.setObjectName(u"bt_save_svc")
        self.bt_save_svc.setGeometry(QRect(250, 517, 61, 21))
        self.bt_save_svc.setFont(font2)
        self.bt_path_svc = QPushButton(self.groupBox_11)
        self.bt_path_svc.setObjectName(u"bt_path_svc")
        self.bt_path_svc.setGeometry(QRect(20, 547, 61, 21))
        self.bt_path_svc.setFont(font2)
        self.e_path_svc = QLineEdit(self.groupBox_11)
        self.e_path_svc.setObjectName(u"e_path_svc")
        self.e_path_svc.setGeometry(QRect(90, 547, 221, 21))
        self.e_path_svc.setFont(font2)
        self.chk_ds9_svc = QCheckBox(self.groupBox_11)
        self.chk_ds9_svc.setObjectName(u"chk_ds9_svc")
        self.chk_ds9_svc.setGeometry(QRect(20, 517, 81, 21))
        self.chk_ds9_svc.setFont(font2)
        self.e_savefilename_svc = QLineEdit(self.groupBox_11)
        self.e_savefilename_svc.setObjectName(u"e_savefilename_svc")
        self.e_savefilename_svc.setGeometry(QRect(90, 570, 221, 21))
        self.e_savefilename_svc.setFont(font2)
        self.label_55 = QLabel(self.groupBox_11)
        self.label_55.setObjectName(u"label_55")
        self.label_55.setGeometry(QRect(20, 570, 61, 20))
        self.label_55.setFont(font3)
        self.label_55.setLayoutDirection(Qt.LeftToRight)
        self.label_55.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.bt_init_SVC = QPushButton(self.groupBox_11)
        self.bt_init_SVC.setObjectName(u"bt_init_SVC")
        self.bt_init_SVC.setGeometry(QRect(260, 417, 61, 21))
        self.bt_init_SVC.setFont(font2)
        self.frame_svc = QFrame(self.groupBox_11)
        self.frame_svc.setObjectName(u"frame_svc")
        self.frame_svc.setGeometry(QRect(0, 22, 331, 331))
        self.frame_svc.setFrameShape(QFrame.NoFrame)
        self.frame_svc.setFrameShadow(QFrame.Raised)
        self.radio_exptime_svc = QRadioButton(self.groupBox_11)
        self.radio_exptime_svc.setObjectName(u"radio_exptime_svc")
        self.radio_exptime_svc.setGeometry(QRect(20, 351, 101, 25))
        self.radio_number_fowler_svc = QRadioButton(self.groupBox_11)
        self.radio_number_fowler_svc.setObjectName(u"radio_number_fowler_svc")
        self.radio_number_fowler_svc.setGeometry(QRect(20, 374, 101, 25))
        self.chk_open_calibration = QCheckBox(Dialog)
        self.chk_open_calibration.setObjectName(u"chk_open_calibration")
        self.chk_open_calibration.setGeometry(QRect(843, 6, 191, 21))
        self.chk_open_calibration.setFont(font)
        self.line = QFrame(Dialog)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(1024, 30, 20, 661))
        self.line.setFrameShape(QFrame.VLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.groupBox_2 = QGroupBox(Dialog)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(350, 27, 671, 51))
        self.radio_H = QRadioButton(self.groupBox_2)
        self.radio_H.setObjectName(u"radio_H")
        self.radio_H.setGeometry(QRect(330, 15, 81, 25))
        font7 = QFont()
        font7.setPointSize(11)
        font7.setBold(True)
        self.radio_H.setFont(font7)
        self.bt_take_image = QPushButton(self.groupBox_2)
        self.bt_take_image.setObjectName(u"bt_take_image")
        self.bt_take_image.setGeometry(QRect(510, 12, 151, 31))
        self.bt_take_image.setFont(font7)
        self.radio_HK_sync = QRadioButton(self.groupBox_2)
        self.radio_HK_sync.setObjectName(u"radio_HK_sync")
        self.radio_HK_sync.setGeometry(QRect(20, 15, 101, 25))
        self.radio_HK_sync.setFont(font7)
        self.radio_SVC = QRadioButton(self.groupBox_2)
        self.radio_SVC.setObjectName(u"radio_SVC")
        self.radio_SVC.setGeometry(QRect(260, 15, 61, 25))
        self.radio_SVC.setFont(font7)
        self.radio_whole_sync = QRadioButton(self.groupBox_2)
        self.radio_whole_sync.setObjectName(u"radio_whole_sync")
        self.radio_whole_sync.setGeometry(QRect(136, 15, 111, 25))
        self.radio_whole_sync.setFont(font7)
        self.radio_K = QRadioButton(self.groupBox_2)
        self.radio_K.setObjectName(u"radio_K")
        self.radio_K.setGeometry(QRect(420, 15, 81, 25))
        self.radio_K.setFont(font7)
        self.groupBox_3 = QGroupBox(Dialog)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(10, 7, 331, 71))
        self.radio_zscale = QRadioButton(self.groupBox_3)
        self.radio_zscale.setObjectName(u"radio_zscale")
        self.radio_zscale.setGeometry(QRect(20, 16, 61, 21))
        self.radio_zscale.setFont(font2)
        self.label_zscale_range = QLabel(self.groupBox_3)
        self.label_zscale_range.setObjectName(u"label_zscale_range")
        self.label_zscale_range.setGeometry(QRect(100, 16, 111, 20))
        self.label_zscale_range.setFont(font3)
        self.label_zscale_range.setLayoutDirection(Qt.LeftToRight)
        self.label_zscale_range.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.e_mscale_min = QLineEdit(self.groupBox_3)
        self.e_mscale_min.setObjectName(u"e_mscale_min")
        self.e_mscale_min.setGeometry(QRect(100, 40, 71, 21))
        self.e_mscale_min.setFont(font2)
        self.e_mscale_min.setAlignment(Qt.AlignCenter)
        self.bt_scale_apply = QPushButton(self.groupBox_3)
        self.bt_scale_apply.setObjectName(u"bt_scale_apply")
        self.bt_scale_apply.setGeometry(QRect(260, 40, 51, 21))
        self.bt_scale_apply.setFont(font2)
        self.radio_mscale = QRadioButton(self.groupBox_3)
        self.radio_mscale.setObjectName(u"radio_mscale")
        self.radio_mscale.setGeometry(QRect(20, 40, 71, 21))
        self.radio_mscale.setFont(font2)
        self.e_mscale_max = QLineEdit(self.groupBox_3)
        self.e_mscale_max.setObjectName(u"e_mscale_max")
        self.e_mscale_max.setGeometry(QRect(180, 40, 71, 21))
        self.e_mscale_max.setFont(font2)
        self.e_mscale_max.setAlignment(Qt.AlignCenter)

        self.retranslateUi(Dialog)

        QMetaObject.connectSlotsByName(Dialog)
    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"Data Taking Package", None))
        self.groupBox_8.setTitle(QCoreApplication.translate("Dialog", u"H Band", None))
        self.label_23.setText(QCoreApplication.translate("Dialog", u"Repeat:", None))
        self.label_61.setText(QCoreApplication.translate("Dialog", u"\\ 16MB", None))
        self.label_57.setText(QCoreApplication.translate("Dialog", u"Start/End :", None))
        self.label_58.setText(QCoreApplication.translate("Dialog", u"Elapsed :", None))
        self.label_prog_time_H.setText(QCoreApplication.translate("Dialog", u"00:00:00.0 / 00:00:00.0", None))
        self.label_54.setText(QCoreApplication.translate("Dialog", u"Status :", None))
        self.label_prog_elapsed_H.setText(QCoreApplication.translate("Dialog", u"0.0 sec", None))
        self.label_prog_sts_H.setText(QCoreApplication.translate("Dialog", u"START/END/TRANSFER/DONE", None))
        self.checkBox_autosave_H.setText(QCoreApplication.translate("Dialog", u"Automatically Save", None))
        self.bt_save_H.setText(QCoreApplication.translate("Dialog", u"SAVE", None))
        self.bt_path_H.setText(QCoreApplication.translate("Dialog", u"Path", None))
        self.label_56.setText(QCoreApplication.translate("Dialog", u"File name:", None))
        self.chk_ds9_H.setText(QCoreApplication.translate("Dialog", u"Show DS9", None))
        self.label_cur_num_H.setText(QCoreApplication.translate("Dialog", u"1 / 1", None))
        self.bt_init_H.setText(QCoreApplication.translate("Dialog", u"H init", None))
        self.radio_number_fowler_H.setText(QCoreApplication.translate("Dialog", u"     N. Fowler:", None))
        self.radio_exptime_H.setText(QCoreApplication.translate("Dialog", u"Exp. Time (s):", None))
        self.groupBox_10.setTitle(QCoreApplication.translate("Dialog", u"K-Band", None))
        self.label_76.setText(QCoreApplication.translate("Dialog", u"\\ 16MB", None))
        self.label_77.setText(QCoreApplication.translate("Dialog", u"Status :", None))
        self.label_prog_time_K.setText(QCoreApplication.translate("Dialog", u"00:00:00.0 / 00:00:00.0", None))
        self.label_74.setText(QCoreApplication.translate("Dialog", u"Elapsed :", None))
        self.label_73.setText(QCoreApplication.translate("Dialog", u"Start/End :", None))
        self.label_prog_elapsed_K.setText(QCoreApplication.translate("Dialog", u"0.0 sec", None))
        self.label_prog_sts_K.setText(QCoreApplication.translate("Dialog", u"START/END/TRANSFER/DONE", None))
        self.label_24.setText(QCoreApplication.translate("Dialog", u"Repeat:", None))
        self.checkBox_autosave_K.setText(QCoreApplication.translate("Dialog", u"Automatically Save", None))
        self.bt_save_K.setText(QCoreApplication.translate("Dialog", u"SAVE", None))
        self.bt_path_K.setText(QCoreApplication.translate("Dialog", u"Path", None))
        self.label_59.setText(QCoreApplication.translate("Dialog", u"File name:", None))
        self.chk_ds9_K.setText(QCoreApplication.translate("Dialog", u"Show DS9", None))
        self.label_cur_num_K.setText(QCoreApplication.translate("Dialog", u"1 / 1", None))
        self.bt_init_K.setText(QCoreApplication.translate("Dialog", u"K Init", None))
        self.radio_exptime_K.setText(QCoreApplication.translate("Dialog", u"Exp. Time (s):", None))
        self.radio_number_fowler_K.setText(QCoreApplication.translate("Dialog", u"     N. Fowler:", None))
        self.groupBox.setTitle(QCoreApplication.translate("Dialog", u"Calibration system control", None))
        self.chk_whole.setText(QCoreApplication.translate("Dialog", u"whole select", None))
        self.bt_run.setText(QCoreApplication.translate("Dialog", u"RUN", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("Dialog", u"Set motor position", None))
        self.bt_ltpos_set1.setText(QCoreApplication.translate("Dialog", u"Set", None))
        self.bt_utpos_set1.setText(QCoreApplication.translate("Dialog", u"Set", None))
        self.bt_utpos_set2.setText(QCoreApplication.translate("Dialog", u"Set", None))
        self.sts_lt_pos1_2.setText(QCoreApplication.translate("Dialog", u"     position 1", None))
        self.bt_ltpos_prev.setText(QCoreApplication.translate("Dialog", u"\u25c0", None))
        self.bt_ltpos_set4.setText(QCoreApplication.translate("Dialog", u"Set", None))
        self.bt_ltpos_set3.setText(QCoreApplication.translate("Dialog", u"Set", None))
        self.bt_ltpos_set2.setText(QCoreApplication.translate("Dialog", u"Set", None))
        self.bt_utpos_next.setText(QCoreApplication.translate("Dialog", u"\u25b6", None))
        self.bt_utpos_prev.setText(QCoreApplication.translate("Dialog", u"\u25c0", None))
        self.bt_ltpos_next.setText(QCoreApplication.translate("Dialog", u"\u25b6", None))
        self.sts_ut_pos1_2.setText(QCoreApplication.translate("Dialog", u"      position 1", None))
        self.sts_ut_pos2_2.setText(QCoreApplication.translate("Dialog", u"position 2", None))
        self.sts_lt_pos2_2.setText(QCoreApplication.translate("Dialog", u"position 2", None))
        self.sts_lt_pos3_2.setText(QCoreApplication.translate("Dialog", u"position 3", None))
        self.sts_lt_pos4_2.setText(QCoreApplication.translate("Dialog", u"position 4", None))
        self.label_3.setText(QCoreApplication.translate("Dialog", u"Upper Translator", None))
        self.label_4.setText(QCoreApplication.translate("Dialog", u"Lower Translator", None))
        self.label_16.setText(QCoreApplication.translate("Dialog", u"moving interval:", None))
        self.bt_ut_motor_init.setText(QCoreApplication.translate("Dialog", u"UT motor init", None))
        self.bt_lt_motor_init.setText(QCoreApplication.translate("Dialog", u"LT motor init", None))
        self.chk_dark.setText(QCoreApplication.translate("Dialog", u"Dark", None))
        self.chk_flat_on.setText(QCoreApplication.translate("Dialog", u"Flat ON", None))
        self.chk_pinhole_ThAr.setText(QCoreApplication.translate("Dialog", u"Pinhole-ThAr", None))
        self.chk_ThAr.setText(QCoreApplication.translate("Dialog", u"Th-Ar", None))
        self.chk_flat_off.setText(QCoreApplication.translate("Dialog", u"Flat OFF", None))
        self.chk_pinhole_flat.setText(QCoreApplication.translate("Dialog", u"Pinhole-Flat", None))
        self.chk_USAF_off.setText(QCoreApplication.translate("Dialog", u"USAP OFF", None))
        self.chk_USAF_on.setText(QCoreApplication.translate("Dialog", u"USAF ON", None))
        self.chk_parking.setText(QCoreApplication.translate("Dialog", u"PARKING", None))
        self.label_67.setText(QCoreApplication.translate("Dialog", u"Frame Type", None))
        self.label_68.setText(QCoreApplication.translate("Dialog", u"Exp. Time", None))
        self.label_80.setText(QCoreApplication.translate("Dialog", u"Repeat", None))
        self.groupBox_11.setTitle(QCoreApplication.translate("Dialog", u"SVC", None))
        self.label_22.setText(QCoreApplication.translate("Dialog", u"Repeat:", None))
        self.label_29.setText(QCoreApplication.translate("Dialog", u"Status :", None))
        self.label_prog_stats_svc.setText(QCoreApplication.translate("Dialog", u"START/END/TRANSFER/DONE", None))
        self.label_25.setText(QCoreApplication.translate("Dialog", u"Start/End :", None))
        self.label_28.setText(QCoreApplication.translate("Dialog", u"Elapsed :", None))
        self.label_prog_time_svc.setText(QCoreApplication.translate("Dialog", u"00:00:00.0 / 00:00:00.0", None))
        self.label_prog_elapsed_svc.setText(QCoreApplication.translate("Dialog", u"0.0 sec", None))
        self.label_31.setText(QCoreApplication.translate("Dialog", u"\\ 16MB", None))
        self.label_cur_num_svc.setText(QCoreApplication.translate("Dialog", u"1 / 1", None))
        self.checkBox_autosave_svc.setText(QCoreApplication.translate("Dialog", u"Automatically Save", None))
        self.bt_save_svc.setText(QCoreApplication.translate("Dialog", u"SAVE", None))
        self.bt_path_svc.setText(QCoreApplication.translate("Dialog", u"Path", None))
        self.chk_ds9_svc.setText(QCoreApplication.translate("Dialog", u"Show DS9", None))
        self.label_55.setText(QCoreApplication.translate("Dialog", u"File name:", None))
        self.bt_init_SVC.setText(QCoreApplication.translate("Dialog", u"SVC Init", None))
        self.radio_exptime_svc.setText(QCoreApplication.translate("Dialog", u"Exp. Time (s):", None))
        self.radio_number_fowler_svc.setText(QCoreApplication.translate("Dialog", u"     N. Fowler:", None))
        self.chk_open_calibration.setText(QCoreApplication.translate("Dialog", u"Open Calibration Box Test", None))
        self.groupBox_2.setTitle("")
        self.radio_H.setText(QCoreApplication.translate("Dialog", u"H-Band", None))
        self.bt_take_image.setText(QCoreApplication.translate("Dialog", u"Take Image / Abort", None))
        self.radio_HK_sync.setText(QCoreApplication.translate("Dialog", u"H && K Sync", None))
        self.radio_SVC.setText(QCoreApplication.translate("Dialog", u"SVC", None))
        self.radio_whole_sync.setText(QCoreApplication.translate("Dialog", u"Whole Sync", None))
        self.radio_K.setText(QCoreApplication.translate("Dialog", u"K-Band", None))
        self.groupBox_3.setTitle("")
        self.radio_zscale.setText(QCoreApplication.translate("Dialog", u"Zscale", None))
        self.label_zscale_range.setText(QCoreApplication.translate("Dialog", u"0 ~ 1000", None))
        self.bt_scale_apply.setText(QCoreApplication.translate("Dialog", u"Apply", None))
        self.radio_mscale.setText(QCoreApplication.translate("Dialog", u"Manual", None))
    # retranslateUi

